/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResetPasswordIndexImport } from './routes/reset-password/index'
import { Route as ForgotPasswordIndexImport } from './routes/forgot-password/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as ActivateAccountIndexImport } from './routes/activate-account/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordIndexRoute = ResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordIndexRoute = ForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const ActivateAccountIndexRoute = ActivateAccountIndexImport.update({
  id: '/activate-account/',
  path: '/activate-account/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/activate-account/': {
      id: '/activate-account/'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof ActivateAccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountIndexRoute
  '/auth': typeof AuthIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountIndexRoute
  '/auth': typeof AuthIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/activate-account/': typeof ActivateAccountIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-account'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-account'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/activate-account/'
    | '/auth/'
    | '/forgot-password/'
    | '/reset-password/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateAccountIndexRoute: typeof ActivateAccountIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateAccountIndexRoute: ActivateAccountIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/activate-account/",
        "/auth/",
        "/forgot-password/",
        "/reset-password/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/activate-account/": {
      "filePath": "activate-account/index.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/forgot-password/": {
      "filePath": "forgot-password/index.tsx"
    },
    "/reset-password/": {
      "filePath": "reset-password/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
